apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: docker-registry

# Labels to add to all resources.
labels:
- includeTemplates: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dockerregistry-operator
    app.kubernetes.io/part-of: dockerregistry-operator
    app.kubernetes.io/version: main
    kyma-project.io/module: docker-registry

resources:
- ./prefixed
- ./network-policy
- ./namespace
