name: 'Setup kyma'
description: 'Action for the kyma setup'

inputs:
  path:
    description: 'path where kyma should be installed'
    required: false
    default: "../bin"

runs:
  using: 'composite'
  steps:
    - name: Install kyma
      shell: bash
      run: |
        mkdir -p ${{ inputs.path }}
        VERSION=$(curl -sL https://api.github.com/repos/kyma-project/cli/releases/latest | jq -r '.tag_name')
        curl -s -L "https://github.com/kyma-project/cli/releases/download/${VERSION}/kyma_$(uname -s)_$(uname -m).tar.gz" | tar -zxvf - -C ${{ inputs.path }} kyma
