# Default values for dockerregistry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: "dockerregistry"
global:
  registryServicePort: 5000
  registryNodePort: 32137
  containerRegistry:
    path: europe-docker.pkg.dev/kyma-project
  images:
    registry:
      name: "registry"
      version: "2.8.3"
      directory: "prod/external"
    registry_init:
      name: "registry-init"
      version: "v20240506-57d31b1d"
      directory: "prod"
  dockerregistryPriorityClassValue: 2000000
  dockerregistryPriorityClassName: "dockerregistry-priority"
dockerRegistry:
  username: "{{ randAlphaNum 20 | b64enc }}" # for gcr "_json_key"
  password: "{{ randAlphaNum 40 | b64enc }}" # for gcr data from json key
  #  This is the registry address, for dockerhub it's username, for other it's url.
  registryAddress: ""
  #  This is the server address of the registry which will be used to create docker configuration.
  serverAddress: ""
docker-registry:
  fullnameOverride: "internal-docker-registry"
  destinationRule:
    enabled: true
  secrets:
    haSharedSecret: "secret"
    htpasswd: "generated-in-init-container"
  extraVolumeMounts:
    - name: htpasswd-data
      mountPath: /data
  extraVolumes:
    - name: registry-credentials
      secret:
        secretName: internal-dockerregistry-config
        items:
          - key: username
            path: username.txt
          - key: password
            path: password.txt
    - name: htpasswd-data
      emptyDir: {}
  rollme: "{{ randAlphaNum 5}}"
  registryHTTPSecret: "{{ randAlphaNum 16 | b64enc }}"
