apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "docker-registry.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tplValue" ( dict "value" .Values.commonLabels "context" . ) | nindent 4 }}
    app.kubernetes.io/instance: {{ template "fullname" . }}-configmap
    app.kubernetes.io/component: {{ template "fullname" . }}
    heritage: {{ .Release.Service }}
data:
  config.yml: |-
{{ toYaml .Values.configData | indent 4 }}
