{{- if or (eq .Values.storage "azure") (eq .Values.storage "s3") (eq .Values.storage "swift") (eq .Values.storage "gcs")}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "docker-registry.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tplValue" ( dict "value" .Values.commonLabels "context" . ) | nindent 4 }}
    app.kubernetes.io/instance: {{ template "fullname" . }}-secret
    app.kubernetes.io/component: {{ template "fullname" . }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if eq .Values.storage "azure" }}
    {{- if and .Values.secrets.azure.accountName .Values.secrets.azure.accountKey .Values.secrets.azure.container }}
  azureAccountName: {{ .Values.secrets.azure.accountName | b64enc | quote }}
  azureAccountKey: {{ .Values.secrets.azure.accountKey | b64enc | quote }}
  azureContainer: {{ .Values.secrets.azure.container | b64enc | quote }}
    {{- end }}
  {{- else if eq .Values.storage "s3" }}
    {{- if and .Values.secrets.s3.secretKey .Values.secrets.s3.accessKey }}
  s3AccessKey: {{ .Values.secrets.s3.accessKey | b64enc | quote }}
  s3SecretKey: {{ .Values.secrets.s3.secretKey | b64enc | quote }}
    {{- end }}
  {{- else if eq .Values.storage "swift" }}
    {{- if and .Values.secrets.swift.username .Values.secrets.swift.password }}
  swiftUsername: {{ .Values.secrets.swift.username | b64enc | quote }}
  swiftPassword: {{ .Values.secrets.swift.password | b64enc | quote }}
    {{- end }}
  {{- else if eq .Values.storage "gcs" }}
    {{- if .Values.secrets.gcs.accountkey }}
  keyfile.json: {{ .Values.secrets.gcs.accountkey | b64enc | quote }}
    {{- end }}
  {{- end }}
  {{- end}}
