apiVersion: v1
kind: Service
metadata:
  name: {{ template "docker-registry.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tplValue" ( dict "value" .Values.commonLabels "context" . ) | nindent 4 }}
    app.kubernetes.io/instance: {{ template "fullname" . }}-svc
    app.kubernetes.io/component: {{ template "fullname" . }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http-{{ .Values.service.name }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.registryNodePort }}
  selector:
    app: {{ template "docker-registry.name" . }}
    release: {{ .Release.Name }}
