apiVersion: operator.kyma-project.io/v1alpha1
kind: DockerRegistry
metadata:
  name: default
  namespace: kyma-system
spec:
  s3:
    bucket: "when I was"
    region: "a young boy"
    regionEndpoint: "my father" # optional
    encrypt: false # optional
    secure: true # optional
    secrets: # optional
      accessKey: "took me into the city"
      secretKey: "to see a marching band"
