apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: dockerregistry-operator-rbac
    app.kubernetes.io/instance: dockerregistry-operator-sa
  name: operator
  namespace: system
