apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

# patch to remove warden from NS
# patches:
#   - path: namespace-without-warden.yaml
#     target:
#       kind: Namespace
#       name: docker-registry
