name: integration tests (push)

on:
  workflow_call:

jobs:
  operator-integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/create-k3d-cluster
      - name: run test
        run: |
          make -C components/operator deploy
          make -C tests/operator test
        env:
          IMG: europe-docker.pkg.dev/kyma-project/prod/dockerregistry-operator:${{ github.sha }}
      - if: ${{ always() }}
        uses: ./.github/actions/collect-cluster-info

  gardener-integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
      - name: save service-account
        shell: bash
        run: 'echo "$GARDENER_SA" > /tmp/gardener-sa.yaml'
        env:
          GARDENER_SA: ${{ secrets.GARDENER_SA }}
      - name: provision gardener
        run: make -C hack provision-gardener
        env:
          GARDENER_SECRET_NAME: ${{ secrets.GARDENER_SECRET_NAME }}
          GARDENER_PROJECT: ${{ secrets.GARDENER_PROJECT }}
          GARDENER_SA_PATH: /tmp/gardener-sa.yaml
      - name: run test
        run: |
          make -C components/operator deploy
          make -C tests/operator test
        env:
          IMG: europe-docker.pkg.dev/kyma-project/prod/dockerregistry-operator:${{ github.sha }}
      - name: deprovision gardener
        if: ${{ always() }}
        run: make -C hack deprovision-gardener
        env:
          GARDENER_SA_PATH: /tmp/gardener-sa.yaml
