name: unit tests

on:
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rebase
      - uses: ./.github/actions/setup-go
      - name: run test
        run: make -C components/operator test
